"""Parameterized operator mismatch family -- the core of the test bed for the "training
operator != deployment operator" direction.

## Why it is needed

LoDoPaB observations are generated by the **official operator** A_true (odl 0.8.1 + astra_cuda,
Parallel2dGeometry, angles uniform(0,pi,1000), detector uniform(-0.1838478, 0.1838478, 513)).
That is the only "true" forward model -- every number on the leaderboard rests on it.

In real deployment the operator held by the reconstruction algorithm is almost never exactly
the one that produced the data: gantry angle calibration drifts, the centre of rotation is not
aligned with the detector centre, the nominal pixel size is slightly off, the angle encoder
jitters. This module writes those as **a family with one continuous parameter**, which turns
the "cost of mismatch" into a measurable, scannable quantity.

## Parameters (delta=0 must reduce bit for bit to the official operator)

  rot        global angle offset Δθ (rad)  -- gantry angle calibration error   [geometric impl]
  det_scale  detector scale factor (1+eps) -- pixel size / magnification error [geometric impl]
  ang_jitter per-angle iid Gaussian jitter (rad) -- angle encoder noise        [geometric impl]
  cor        detector centre offset (m)    -- classic CT alignment error [explicit synthesis]

Physical magnitudes: pixel width 0.7168 mm; angular step pi/1000 = 3.1416 mrad. So cor =
det_cell() is exactly **one pixel** and rot = ANG_STEP is exactly **one angular step**. Mismatch
amounts must be reported as "how many pixels / how many angular steps" for a reader to judge
whether they are realistic.

## Why cor cannot use a geometric implementation (a lesson paid for on 2026-08-28)

The first version wrote cor as `uniform_partition(-half+cor, half+cor, N_DET)`, which is
conceptually correct, but **ODL's astra backend silently discards the detector offset in 2D
parallel beam** -- astra_setup.py:499 still carries `# TODO: change to parallel_vec when
available`, and the `create_proj_geom('parallel', det_width, det_count, angles)` called on
line 506 has no offset parameter at all.
Consequence: the whole COR mismatch curve would come out flat, and a flat line looks exactly
like "our method is very robust to COR" -- the most dangerous false positive in this direction.
Guard 2 caught it on the very first run (relative change 0.00e+00).

The correct implementation follows the definition: when the detector as a whole is offset by d,
bin i measures the ray at s_i - d, i.e. y_meas = S_d(A_official x), where S_d is a sub-pixel
shift along the detector axis. Hence
        A_cor = S_d ∘ A_official
which is **exact** (not an approximation) and independent of the backend.

## Anti-cheating conventions
  1. delta=0 returns bit for bit to the official operator (check_zero_reduces_to_official, atol=0);
  2. every parameter must measurably change the sinogram at the "one pixel / one angular step"
     scale (check_perturbation_is_alive);
  3. the ground truth stays with the harness; a method only gets the observation and "the
     operator it believes in".
"""
import math
import numpy as np

IMG_SHAPE = (362, 362)
FOV_HALF = 0.13                 # m
N_ANG, N_DET = 1000, 513
ANG_STEP = math.pi / N_ANG      # 0.0031416 rad

_CACHE = {}


# --------------------------------- single source of geometry constants ----
def official_geometry():
    """Official parallel_beam_geometry (cached).

    Constants must never be transcribed by hand: the first version hand-copied
    DET_HALF=0.18384776, which differs from odl's own 0.13*sqrt(2) by 3.1e-9, and the guard
    caught it immediately -- that would quietly introduce a 4e-6 pixel mismatch, while every
    conclusion in this project rests on "delta=0 equals the official operator bit for bit".
    """
    if "geom" not in _CACHE:
        import odl
        import odl.tomo as odl_tomo
        domain = odl.uniform_discr([-FOV_HALF, -FOV_HALF], [FOV_HALF, FOV_HALF],
                                   IMG_SHAPE, dtype=np.float32)
        _CACHE["geom"] = odl_tomo.parallel_beam_geometry(
            domain, num_angles=N_ANG, det_shape=(N_DET,))
    return _CACHE["geom"]


def det_half():
    """Detector half-span (m), taken from the official geometry itself."""
    return float(official_geometry().det_partition.max_pt[0])


def det_cell():
    """Detector pixel width (m) -- the denominator of the "how many pixels" reporting convention."""
    return float(official_geometry().det_partition.cell_sides[0])


def describe(rot=0.0, det_scale=1.0, cor=0.0, ang_jitter=0.0):
    """Translate mismatch parameters into physical units (pixels / angular steps) -- reports must use this convention."""
    return {
        "rot_rad": rot, "rot_in_steps": rot / ANG_STEP,
        "det_scale": det_scale, "det_scale_ppm": (det_scale - 1) * 1e6,
        "cor_m": cor, "cor_in_pixels": cor / det_cell(),
        "ang_jitter_rad": ang_jitter, "ang_jitter_in_steps": ang_jitter / ANG_STEP,
    }


# --------------------------------- sub-pixel shift along detector axis ----
def shift_detector(y, pixels):
    """S_d: shift by `pixels` detector pixels along the detector axis (linear interpolation,
    differentiable, zero padding).

    y: (..., N_ANG, N_DET) torch. pixels>0 means the signal moves in the +s direction (i.e. bin
    i reads the value that used to sit at s_{i-pixels}), which matches "the detector as a whole
    is offset towards +s".
    """
    import torch
    if pixels == 0.0:
        return y
    idx = torch.arange(N_DET, device=y.device, dtype=y.dtype) - pixels
    i0 = torch.floor(idx)
    w = (idx - i0)
    i0 = i0.long()
    i1 = i0 + 1
    valid0 = (i0 >= 0) & (i0 < N_DET)
    valid1 = (i1 >= 0) & (i1 < N_DET)
    g0 = torch.where(valid0, i0.clamp(0, N_DET - 1), torch.zeros_like(i0))
    g1 = torch.where(valid1, i1.clamp(0, N_DET - 1), torch.zeros_like(i1))
    y0 = y[..., g0] * valid0.to(y.dtype)
    y1 = y[..., g1] * valid1.to(y.dtype)
    return y0 * (1 - w) + y1 * w


def shift_detector_adjoint(g, pixels):
    """S_d^T: the exact transpose of the shift operator (scattering by definition, without
    assuming it equals some reverse shift).

    The forward is out[k] = y[i0[k]]*(1-w[k]) + y[i0[k]+1]*w[k], so the transpose **scatters**
    g[k] back to i0[k], i0[k]+1 with the same weights.

    Measured note (2026-08-28): the guard incidentally tested the lazy version that simply uses
    S_{-d} as the transpose, and it passes **too** (relative difference 3.2e-7). The reason is
    that under a constant shift S_d is a translation-invariant convolution (w[k]=frac(-d) does
    not depend on k), whose transpose is exactly the reverse shift of the flipped kernel =
    S_{-d}. So the two are identically equal here, and that is not a coincidence. The explicit
    scatter implementation is kept anyway: if the shift ever becomes angle-dependent (for
    example a COR that drifts with angle) the identity stops holding, and the guard will be
    there to find it for us.
    """
    import torch
    if pixels == 0.0:
        return g
    idx = torch.arange(N_DET, device=g.device, dtype=g.dtype) - pixels
    i0 = torch.floor(idx)
    w = idx - i0
    i0 = i0.long()
    out = torch.zeros_like(g)
    for off, wt in ((0, 1.0 - w), (1, w)):
        j = i0 + off
        ok = (j >= 0) & (j < N_DET)
        out.index_add_(-1, j.clamp(0, N_DET - 1), g * (wt * ok.to(g.dtype)))
    return out


def perturb_observation(y, rot=0.0, det_scale=1.0, cor=0.0, ang_jitter=0.0, seed=0):
    """Resample a **real measurement** into the sinogram that "a machine with slightly different
    geometry would have measured".

    Why this is needed (rather than only perturbing the method's "belief"):
      for training-free variational methods, "data from G(δ), belief G(0)" and "data from G(0),
      belief G(δ)" are the same thing (up to the sign of δ), so scanning the belief is enough.
      For **learned** methods it is not: the network weights are pinned to the operator used at
      training time, so changing the data and changing the belief are two different
      perturbations. To measure the learned side and the classical side with the same ruler,
      the data really has to be perturbed.

    This is not a simulation: S_d is the definition of a detector offset, and resampling along
    the angle axis is the interpolation approximation of the same object measured at slightly
    different angles. The noise is still LoDoPaB's real Poisson noise, and no step uses the
    ground truth.
    """
    import torch
    single = (y.dim() == 2)
    yb = y[None] if single else y
    if det_scale != 1.0:
        # detector pixel grows by (1+eps): bin i corresponds to physical position s_i*(1+eps),
        # resampled onto the original sampling
        pos = (torch.arange(N_DET, device=yb.device, dtype=yb.dtype)
               - (N_DET - 1) / 2.0) * det_scale + (N_DET - 1) / 2.0
        yb = _interp_last(yb, pos)
    if rot != 0.0 or ang_jitter != 0.0:
        base = torch.arange(N_ANG, device=yb.device, dtype=yb.dtype)
        shift = rot / ANG_STEP
        if ang_jitter != 0.0:
            rng = np.random.default_rng(seed)
            j = torch.tensor(rng.normal(0.0, ang_jitter / ANG_STEP, N_ANG),
                             device=yb.device, dtype=yb.dtype)
            shift = shift + j
        yb = _interp_angle(yb, base + shift)
    if cor != 0.0:
        yb = shift_detector(yb, cor / det_cell())
    return yb[0] if single else yb


def _interp_last(y, pos):
    """Linear resampling along the last (detector) axis at float indices pos, zero outside."""
    import torch
    i0 = torch.floor(pos)
    w = pos - i0
    i0 = i0.long()
    out = torch.zeros_like(y)
    for off, wt in ((0, 1 - w), (1, w)):
        j = i0 + off
        ok = (j >= 0) & (j < N_DET)
        out = out + y[..., j.clamp(0, N_DET - 1)] * (wt * ok.to(y.dtype))
    return out


def _interp_angle(y, pos):
    """Resample along the angle axis at float indices. The angle axis is periodic on [0,pi), but
    the periodicity comes with a detector flip (p(θ+pi, s) = p(θ, -s)), so out-of-range indices
    use the flipped row rather than a plain wrap."""
    import torch
    i0 = torch.floor(pos)
    w = (pos - i0).view(1, -1, 1)
    i0 = i0.long()
    out = torch.zeros_like(y)
    for off, wt in ((0, 1 - w), (1, w)):
        j = i0 + off
        wrapped = (j < 0) | (j >= N_ANG)
        jm = j % N_ANG
        v = y[:, jm, :]
        v = torch.where(wrapped.view(1, -1, 1), v.flip(-1), v)
        out = out + v * wt
    return out


# ------------------------------------------------------------ operator ----
class MismatchedOperator:
    """The only operator object available on the method side: project / adjoint-free / fbp / params.

    project(x): (362,362) or (B,362,362) -> (...,1000,513), differentiable in torch.
    fbp(y):     (1000,513) torch -> (362,362) torch; with cor set, shift back first and then
                filter and backproject (a method that "believes" the detector is offset by d
                should undo d in its FBP).
    """

    def __init__(self, rot=0.0, det_scale=1.0, cor=0.0, ang_jitter=0.0, seed=0,
                 device="cuda:0", impl="astra_cuda", fbp_fs=0.1):
        import odl
        import odl.tomo as odl_tomo
        from odl.contrib.torch import OperatorModule

        self.device = device
        self.cor_pixels = cor / det_cell()
        self._mods = {}
        domain = odl.uniform_discr([-FOV_HALF, -FOV_HALF], [FOV_HALF, FOV_HALF],
                                   IMG_SHAPE, dtype=np.float32)
        if ang_jitter == 0.0:
            angle_part = odl.uniform_partition(0.0 + rot, math.pi + rot, N_ANG)
        else:
            base = np.linspace(0.0, math.pi, N_ANG, endpoint=False) + rot
            rng = np.random.default_rng(seed)
            angle_part = odl.nonuniform_partition(
                np.sort(base + rng.normal(0.0, ang_jitter, N_ANG)))
        half = det_half() * det_scale
        # Note: the detector offset is [not] written into the partition -- astra silently drops it (see module docstring).
        det_part = odl.uniform_partition(-half, half, N_DET)
        self.geometry = odl_tomo.Parallel2dGeometry(angle_part, det_part)
        self.rt = odl_tomo.RayTransform(domain, self.geometry, impl=impl)
        self._rt_mod = OperatorModule(self.rt).to(device)
        self._fbp = odl_tomo.fbp_op(self.rt, filter_type="Hann",
                                    frequency_scaling=fbp_fs)
        self.params = describe(rot, det_scale, cor, ang_jitter)

    def project(self, x):
        import torch
        single = (x.dim() == 2)
        xb = x[None] if single else x
        y = self._rt_mod(xb.to(self.device))
        y = shift_detector(y, self.cor_pixels)
        return y[0] if single else y

    def adjoint(self, y):
        """A^T = A_official^T ∘ S_d^T. Unrolled networks use it at every iteration."""
        import torch
        if "adj" not in self.__dict__:
            from odl.contrib.torch import OperatorModule
            self.adj = OperatorModule(self.rt.adjoint).to(self.device)
        single = (y.dim() == 2)
        yb = y[None] if single else y
        yb = shift_detector_adjoint(yb.to(self.device), self.cor_pixels)
        x = self.adj(yb)
        return x[0] if single else x

    def fbp(self, y):
        """FBP at the default fbp_fs (numpy path, for initializing variational methods)."""
        import torch
        y = shift_detector(y.to(self.device), -self.cor_pixels)
        arr = np.asarray(self._fbp(y.detach().cpu().numpy()))
        return torch.tensor(arr, dtype=torch.float32, device=self.device)

    def make_fbp(self, fs):
        """FBP callable (op_init for unrolled networks, used on every forward pass).

        ## Performance warning (confirmed with py-spy on 2026-08-28, do not step on it again)

        This path is **not fully on the GPU**. odl's `fbp_op` puts the ramp filter on the
        **CPU numpy FFT** (py-spy stack top `numpy/fft/_pocketfft.py:70`), independently of
        impl="astra_cuda". Consequence: every training step performs a 1000x513 CPU FFT.
        **A single training process is tolerable (2.27 step/s measured for LPD), but two
        processes running at once fight over the CPU and both slow down until the logs stop
        advancing** -- that time I misdiagnosed it as an HDF5 file lock and moved 8.8 GB of data
        to local disk for nothing.

        => discipline: run only one process that calls this heavily at a time; or precompute and
          cache the FBP results (which is the route train_fbpunet.py takes).

        Alternatives tried: rewriting the filter on the GPU with torch.fft. The discrete Ram-Lak
        kernel version differs from odl by 1.5%, and rewriting it against odl's formula
        (norm_freq·cos²(norm_freq·π/(2fs))) is worse still at 5-13% -- odl has further
        conventions on physical frequency units and padding. **A fast path that has not been
        cross-checked must not be used for training**, so the slow but correct one is kept.
        Optimize only after the cross-check passes.
        """
        import odl.tomo as odl_tomo
        from odl.contrib.torch import OperatorModule
        key = ("fbp", round(float(fs), 6))
        if key not in self._mods:
            self._mods[key] = OperatorModule(
                odl_tomo.fbp_op(self.rt, filter_type="Hann",
                                frequency_scaling=float(fs))).to(self.device)
        mod = self._mods[key]

        def _fbp(y):
            return mod(shift_detector(y.to(self.device), -self.cor_pixels))
        return _fbp


def make_operator(**kw):
    return MismatchedOperator(**kw)


# -------------------------------------------------------------- guards ----
def check_zero_reduces_to_official(atol=0.0):
    """Guard 1: the delta=0 geometry must agree bit for bit with the official partition."""
    official = official_geometry()
    import odl
    import odl.tomo as odl_tomo
    mine = odl_tomo.Parallel2dGeometry(
        odl.uniform_partition(0.0, math.pi, N_ANG),
        odl.uniform_partition(-det_half(), det_half(), N_DET))
    da = float(np.abs(official.angles - mine.angles).max())
    dd = float(np.abs(official.det_partition.grid.coord_vectors[0]
                      - mine.det_partition.grid.coord_vectors[0]).max())
    if da > atol or dd > atol:
        raise RuntimeError(
            f"delta=0 did not reduce to the official operator: max angle diff {da:.3e}, max detector diff {dd:.3e}")
    return {"angle_maxdiff": da, "det_maxdiff": dd}


def check_perturbation_is_alive(x, rel_tol=1e-6, device="cuda:0"):
    """Guard 2: every mismatch parameter must genuinely change the sinogram at the "one pixel /
    one angular step" scale.

    A dead parameter (silently dropped by the backend, or a misspelled key) flattens the
    mismatch curve, and a flat line looks exactly like "the method is very robust" -- the most
    dangerous false positive in this direction. **Report all of them, then raise**, so it is
    clear at a glance which ones are alive.
    """
    import torch
    base = make_operator(device=device)
    y0 = base.project(x.to(device))
    scale = float(y0.abs().mean())
    probes = {"rot": dict(rot=ANG_STEP), "det_scale": dict(det_scale=1.0 + 1e-3),
              "cor": dict(cor=det_cell()), "ang_jitter": dict(ang_jitter=ANG_STEP)}
    out, dead = {}, []
    for name, kw in probes.items():
        op = make_operator(device=device, **kw)
        y = op.project(x.to(device))
        rel = float((y - y0).abs().mean()) / max(scale, 1e-30)
        out[name] = rel
        if rel < rel_tol:
            dead.append(f"{name}({rel:.2e})")
        del op, y
        torch.cuda.empty_cache()
    if dead:
        raise RuntimeError(
            f"dead mismatch parameters: {', '.join(dead)} -- the parameter never reached the operator; refusing to start. "
            f"all probes: {out}")
    return out


def check_data_and_operator_agree(x, device="cuda:0"):
    """Guard 4: data-side and operator-side perturbations must corroborate each other.

    For a noiseless projection we should have  A(δ) x  ==  perturb(A(0) x, δ) -- two entirely
    independent code paths (one modifies the odl geometry, one resamples the tensor) computing
    the same thing. If either side is wrong (flipped sign, wrong unit, swapped axis), this
    identity breaks immediately.

    Thresholds are set per axis (magnitudes measured on 2026-08-28: cor 0.0, rot 4.2e-10,
    det_scale 1.7e-4, ang_jitter 1.5e-3). cor and rot at an integer angular step involve no
    interpolation, so near-exactness is required; the scale and jitter axes go through
    interpolation and are relaxed to 1e-2. **A guard without a threshold is not a guard, it is a
    diagnostic** -- the first version only printed numbers without raising, which amounts to
    letting it "pass" forever.
    """
    import torch
    base = make_operator(device=device)
    y0 = base.project(x.to(device))
    out = {}
    probes = {"cor": dict(cor=det_cell()), "rot": dict(rot=ANG_STEP),
              "det_scale": dict(det_scale=1.0 + 1e-3),
              "ang_jitter": dict(ang_jitter=ANG_STEP)}
    tol = {"cor": 1e-6, "rot": 1e-6, "det_scale": 1e-2, "ang_jitter": 1e-2}
    bad = []
    for name, kw in probes.items():
        op = make_operator(device=device, **kw)
        via_op = op.project(x.to(device))
        via_data = perturb_observation(y0, **kw)
        # the outermost columns are affected by zero padding, so compare the interior
        a, b = via_op[..., 10:-10], via_data[..., 10:-10]
        rel = float((a - b).abs().mean() / a.abs().mean())
        out[name] = rel
        if rel > tol[name]:
            bad.append(f"{name}({rel:.2e} > {tol[name]:.0e})")
        del op
        torch.cuda.empty_cache()
    if bad:
        raise RuntimeError(
            f"data-side and operator-side perturbations disagree: {', '.join(bad)} -- one of the two implementations is wrong. "
            f"all: {out}")
    return out


def check_shift_is_exact(atol=1e-5):
    """Guard 3: at integer shifts, the sub-pixel shift must agree element-wise with a true index
    shift.

    A linear-interpolation implementation is easiest to get wrong in direction or sign; an
    integer shift is the one case with a closed-form answer, and therefore the only test case
    that can force the bug out. It also verifies that the reverse shift restores the input
    (+d then -d).
    """
    import torch
    g = torch.Generator().manual_seed(0)
    y = torch.randn(3, N_ANG, N_DET, generator=g)
    k = 7
    got = shift_detector(y, float(k))
    want = torch.zeros_like(y)
    want[..., k:] = y[..., :-k]           # bin i reads s_{i-k}
    err = float((got - want).abs().max())
    if err > atol:
        raise RuntimeError(f"integer shift is not exact: max diff {err:.3e} (direction or sign reversed)")
    back = shift_detector(shift_detector(y, 3.0), -3.0)
    rt = float((back[..., 10:-10] - y[..., 10:-10]).abs().max())
    if rt > atol:
        raise RuntimeError(f"shift is not invertible: max round-trip diff {rt:.3e}")
    # S_d^T must be a true transpose: <S_d a, b> == <a, S_d^T b>. Only a non-integer shift
    # exposes the most common lazy version, "passing off S_{-d} as the transpose".
    a = torch.randn(2, N_ANG, N_DET, generator=g)
    bb = torch.randn(2, N_ANG, N_DET, generator=g)
    p = 2.37
    lhs = float((shift_detector(a, p) * bb).sum())
    rhs = float((a * shift_detector_adjoint(bb, p)).sum())
    adj_err = abs(lhs - rhs) / max(abs(lhs), 1e-30)
    if adj_err > 1e-4:
        raise RuntimeError(f"the adjoint of the shift is not exact: relative diff {adj_err:.3e}")
    fake = float(abs((a * shift_detector(bb, -p)).sum() - lhs) / max(abs(lhs), 1e-30))
    return {"int_shift_err": err, "roundtrip_err": rt, "adjoint_rel_err": adj_err,
            "naive_minus_d_rel_err": fake}
