"""Run TVAdam with the official operator (ODL + astra_cuda, exact dival spec) -- the last piece
of the cross-check.

Why it came to this (the full chain, 2026-08-27):
  FBP was already aligned (30.51 vs 30.19) but the TV gain was 2.4 dB short; crime tier A (our
  own operator generating and solving) gave 34.7 on the first image => the recipe is innocent.
  Root cause: the LoDoPaB observations were generated by the official operator in the first
  place, and the reconstruction operator used by every method on the leaderboard is the discrete
  twin of the generating operator -- **this benchmark is essentially an inverse-crime benchmark**,
  so the cross-check must use the official operator. Our FastRadon is not "bad", it is hard-
  fitting through a systematic mismatch of order 0.05 inside somebody else's crime setting.

Spec (checked line by line against dival/datasets/lodopab_dataset.py):
  domain   = uniform_discr([-0.13,-0.13],[0.13,0.13],(362,362))   # metres
  geometry = parallel_beam_geometry(domain, num_angles=1000, det_shape=(513,))
  impl     = astra_cuda
  FBP init = odl_tomo.fbp_op(rt, filter_type='Hann', frequency_scaling=0.1)
  gamma    = 20.556 (official json), 5000 iter, poisson loss
"""
import os
os.environ.setdefault("CUDA_VISIBLE_DEVICES", "5")
import sys, time, warnings
warnings.filterwarnings("ignore")
import numpy as np
import torch

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
from lodopab import load_batch, psnr, ssim          # noqa: E402
from tv_adam import poisson_loss, tv_aniso          # noqa: E402

os.makedirs(os.path.join(HERE, "..", "results"), exist_ok=True)
LOG = os.path.join(HERE, "..", "results", "official_op.txt")


def log(m):
    print(m, flush=True)
    with open(LOG, "a") as f:
        f.write(m + "\n")


def main():
    import odl
    import odl.tomo as odl_tomo      # odl 0.8.1 (the dival-era version; the 1.0 API changed a lot)
    from odl.contrib.torch import OperatorModule
    dev = "cuda:0"          # under CUDA_VISIBLE_DEVICES=5 this is physical card 5

    domain = odl.uniform_discr([-0.13, -0.13], [0.13, 0.13], (362, 362),
                               dtype=np.float32)
    geometry = odl_tomo.parallel_beam_geometry(domain, num_angles=1000,
                                               det_shape=(513,))
    rt = odl_tomo.RayTransform(domain, geometry, impl="astra_cuda")
    rt_mod = OperatorModule(rt).to(dev)
    fbp = odl_tomo.fbp_op(rt, filter_type="Hann", frequency_scaling=0.1)

    obs, gt = load_batch(16, 0, "cpu")
    log("== official operator %s ==" % time.strftime("%F %T"))

    # self_check for the official operator: the residual of A(gt) against the real observation should be ~ pure noise
    y0 = rt(gt[0].numpy())
    resid = float(np.sum((np.asarray(y0) - obs[0].numpy()) ** 2))
    log("official operator A(gt#0) residual = %.3f (our FastRadon on the same image: 3.10)" % resid)

    gamma, iters = 20.556, 5000
    log("TVAdam (official operator, γ=%.3f, %d iter, poisson)" % (gamma, iters))
    po, so = [], []
    for i in range(16):
        t0 = time.time()
        x0 = torch.tensor(np.asarray(fbp(obs[i].numpy())),
                          dtype=torch.float32, device=dev).requires_grad_(True)
        y = obs[i].to(dev)
        opt = torch.optim.Adam([x0], lr=1e-3)
        best_l, best_x = float("inf"), x0.detach().clone()
        for k in range(iters):
            opt.zero_grad()
            pred = rt_mod(x0[None])[0]
            loss = poisson_loss(pred, y) + gamma * tv_aniso(x0)
            loss.backward()
            opt.step()
            l = float(loss.detach())
            if l < best_l:
                best_l, best_x = l, x0.detach().clone()
        r = best_x.cpu()
        po.append(psnr(r, gt[i], "adaptive"))
        so.append(ssim(r, gt[i], "adaptive"))
        log("  #%-2d  %.2f / %.3f  (%.0fs)" % (i, po[-1], so[-1], time.time() - t0))
    po, so = np.array(po), np.array(so)
    log("TVAdam@official operator  official PSNR %.2f ± %.2f   official SSIM %.3f ± %.3f"
        % (po.mean(), po.std(), so.mean(), so.std()))
    log("reference: our operator on the same 16 images 32.03; official challenge 33.36")


if __name__ == "__main__":
    main()
