"""LoDoPaB forward simulation -- used on the [training side] only; the evaluation side always
uses the real measurement files.

## Methodological position (why simulation is allowed only on the training side)

Mismatch experiments need "training operator != deployment operator". LoDoPaB only provides real
observations generated by the official operator A_true, so producing a mismatch requires one
side to be generated by us. Two ways to place it:

  (X) train on real data, test on simulated data -- the test side becomes an inverse crime: the
      method under test shares a discretization with whoever set the exam, and the score is
      inflated (crime/ in this repository measured tier A at 33.66 against 33.83 on real data,
      which is structurally not comparable).
  (O) train on simulated data, test on real data -- the evaluation always stands on real
      measurements, and the simulation only affects "what the network has seen", which is the
      definition of mismatch itself.

This module implements (O). And **every** training set (including the delta=0 control) goes
through simulation, so delta is the only variable -- otherwise the "real vs simulated" crime gap
would leak into the mismatch curve.

## Noise model (official dival/LoDoPaB spec)

  normalization: ground truth x ∈ [0,1] corresponds to attenuation mu = x * MU_MAX
  counts:        N ~ Poisson(N0 * exp(-MU_MAX * A x)),  N0 = 4096 photons per pixel
  post-log:      y = -log(N / N0) / MU_MAX

  MU_MAX = 81.35858, N0 = 4096 -- the same source as poisson_loss in harness/tv_adam.py; the two
  must agree, otherwise the loss function and the data generation are inconsistent.
"""
import torch

MU_MAX = 81.35858
N0 = 4096.0


def simulate_observation(x, operator, generator=None, clip_min=0.1):
    """Generate a noisy post-log observation from ground truth x and the operator.

    x: (B,362,362) or (362,362), values in [0,1].
    clip_min: lower bound on counts, to prevent log(0). 0.1 photons is far below the noise level,
    so it does not change the statistics and only prevents overflow.
    """
    y_clean = operator.project(x)
    rate = N0 * torch.exp(-MU_MAX * y_clean)
    counts = torch.poisson(rate, generator=generator)
    counts = counts.clamp_min(clip_min)
    return -torch.log(counts / N0) / MU_MAX


# -------------------------------------------------------------- guards ----
def check_matches_real(gt, obs_real, operator, atol_rel=0.08):
    """Guard: with delta=0 the simulated observation must agree statistically with the [real
    observation].

    If simulation and reality are far apart, then the methodological choice of "simulate on the
    training side" is itself bad -- the starting point of the mismatch curve would be
    contaminated by an unknown crime gap. Two things are checked:
      1. the relative difference between the noiseless forward A(gt) and the real observation
         (order ~3%, known in this repository);
      2. the ratio between the per-bin standard deviation of the simulated noise and that of the
         real residual (should be ~1).
    """
    y_clean = operator.project(gt)
    rel = float((y_clean - obs_real).abs().mean() / obs_real.abs().mean())
    g = torch.Generator(device=y_clean.device).manual_seed(0)
    y_sim = simulate_observation(gt, operator, generator=g)
    sd_sim = float((y_sim - y_clean).std())
    sd_real = float((obs_real - y_clean).std())
    ratio = sd_sim / max(sd_real, 1e-30)
    ok = (rel < atol_rel) and (0.7 < ratio < 1.4)
    if not ok:
        raise RuntimeError(
            f"simulation does not match the real observation: noiseless relative difference {rel:.3f} (limit {atol_rel}), "
            f"noise std ratio {ratio:.3f} (limit 0.7-1.4) -- training-side simulation is unusable")
    return {"clean_rel_diff": rel, "noise_sd_ratio": ratio,
            "sd_sim": sd_sim, "sd_real": sd_real}
