"""LoDoPaB forward simulation -- used on the training side only. Evaluation always uses
the real measurement files.

## Methodological position (why simulation is allowed on the training side only)

The mismatch experiment needs "training operator != deployment operator". LoDoPaB provides
only real observations generated by the official operator A_true, so producing a mismatch
means one side has to be generated by us. Two ways to place it:

  (X) train on real data, test on simulated data -- the test side becomes an inverse
      crime: the method under test shares its discretization with the examiner, and the
      score is inflated (crime/ in this repository measured tier A at 33.66 against 33.83
      on real data for the same images; structurally not comparable).
  (O) train on simulated data, test on real data -- evaluation always stands on real
      measurements, and simulation only affects "what the network has seen", which is the
      definition of mismatch itself.

This module implements (O). And *all* training sets, including the delta = 0 control, go
through simulation, so that delta is the only variable -- otherwise the real-vs-simulated
crime gap leaks into the mismatch curve.

## Noise model (dival / LoDoPaB official specification)

  normalization: ground truth x in [0,1] corresponds to attenuation mu = x * MU_MAX
  counts:        N ~ Poisson(N0 * exp(-MU_MAX * A x)),  N0 = 4096 photons per pixel
  post-log:      y = -log(N / N0) / MU_MAX

  MU_MAX = 81.35858, N0 = 4096 -- the same constants as poisson_loss in harness/tv_adam.py.
  The two must agree, or the loss is inconsistent with the data generation.
"""
import torch

MU_MAX = 81.35858
N0 = 4096.0


def simulate_observation(x, operator, generator=None, clip_min=0.1):
    """Noisy post-log observation from ground truth x and an operator.

    x: (B,362,362) or (362,362), values in [0,1].
    clip_min: lower bound on the counts against log(0). 0.1 photon is far below the noise
    level, so the statistics are unchanged; it only prevents overflow.
    """
    y_clean = operator.project(x)
    rate = N0 * torch.exp(-MU_MAX * y_clean)
    counts = torch.poisson(rate, generator=generator)
    counts = counts.clamp_min(clip_min)
    return -torch.log(counts / N0) / MU_MAX


# ------------------------------------------------------------------ guard ----
def check_matches_real(gt, obs_real, operator, atol_rel=0.08):
    """Guard: the delta = 0 simulated observation must agree statistically with the *real*
    observation.

    If simulation and reality are far apart, the methodological choice "simulate on the
    training side" is itself broken -- the start of the mismatch curve is contaminated by an
    unknown crime gap. Two checks:
      1. relative difference between the noise-free forward A(gt) and the real observation
         (about 3% in this repository);
      2. ratio of the per-bin standard deviation of the simulated noise to that of the real
         residual (should be about 1).
    """
    y_clean = operator.project(gt)
    rel = float((y_clean - obs_real).abs().mean() / obs_real.abs().mean())
    g = torch.Generator(device=y_clean.device).manual_seed(0)
    y_sim = simulate_observation(gt, operator, generator=g)
    sd_sim = float((y_sim - y_clean).std())
    sd_real = float((obs_real - y_clean).std())
    ratio = sd_sim / max(sd_real, 1e-30)
    ok = (rel < atol_rel) and (0.7 < ratio < 1.4)
    if not ok:
        raise RuntimeError(
            f"simulation does not match the real observation: noise-free relative difference "
            f"{rel:.3f} (limit {atol_rel}), noise std ratio {ratio:.3f} (limit 0.7-1.4) -- "
            f"training-side simulation is unusable")
    return {"clean_rel_diff": rel, "noise_sd_ratio": ratio,
            "sd_sim": sd_sim, "sd_real": sd_real}
